"""Initial migration

Revision ID: a6517b00bf39
Revises: 41a32bc09775
Create Date: 2024-09-25 00:57:16.794509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6517b00bf39'
down_revision = '41a32bc09775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('client_billing_time')
        batch_op.drop_column('employee_delivery_time')
        batch_op.drop_column('case_size')
        batch_op.drop_column('review_progress')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.drop_column('billing_description')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('commission_value')
        batch_op.drop_column('base_value')
        batch_op.drop_column('case_count')
        batch_op.drop_column('commission_base')
        batch_op.drop_column('compensation_type')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('complete_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compensation_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('commission_base', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('case_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('commission_value', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_progress', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('case_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('employee_delivery_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('client_billing_time', sa.DATETIME(), nullable=True))

    op.create_table('process',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('case_quality', sa.VARCHAR(length=50), nullable=False),
    sa.Column('process_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
